version: "3.7"

services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9050:9050"
    environment:
      SERVER_PORT: 9050
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"
  kafka:
    image: obsidiandynamics/kafka
    restart: "no"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8000:8000"
    depends_on:
      - "kafka"
      - "discovery-service"
      - "class-service"
      - "lecturer-service"
      - "point-service"
      - "student-service"
      - "subject-service"
      - "user-service"

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8761:8761"
    depends_on:
      - "kafka"

  class-mysql:
    image: mysql
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: class-db

  class-service:
    build:
      context: ./class-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8002:8002"
    depends_on:
      - "kafka"
      - "class-mysql"
    environment:
      - spring.datasource.url=jdbc:mysql://class-mysql:3306/class-db?createDatabaseIfNotExist=True
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update

  lecturer-mysql:
    image: mysql
    restart: "no"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lecturer-db

  lecturer-service:
    build:
      context: ./lecturer-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8003:8003"
    depends_on:
      - "kafka"
      - "lecturer-mysql"
    environment:
      - spring.datasource.url=jdbc:mysql://lecturer-mysql:3306/lecturer-db?createDatabaseIfNotExist=True
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update

  point-mysql:
    image: mysql
    restart: "no"
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: point-db

  point-service:
    build:
      context: ./point-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8004:8004"
    depends_on:
      - "kafka"
      - "point-mysql"
    environment:
      - spring.datasource.url=jdbc:mysql://point-mysql:3306/point-db?createDatabaseIfNotExist=True
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update

  student-mysql:
    image: mysql
    restart: "no"
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student-db

  student-service:
    build:
      context: ./student-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8005:8005"
    depends_on:
      - "kafka"
      - "student-mysql"
    environment:
      - spring.datasource.url=jdbc:mysql://student-mysql:3306/student-db?createDatabaseIfNotExist=True
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update

  subject-mysql:
    image: mysql
    restart: "no"
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: subject-db

  subject-service:
    build:
      context: ./subject-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8006:8006"
    depends_on:
      - "kafka"
      - "subject-mysql"
    environment:
      - spring.datasource.url=jdbc:mysql://subject-mysql:3306/subject-db?createDatabaseIfNotExist=True
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update

  user-mysql:
    image: mysql
    restart: "no"
    ports:
      - "3311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user-db

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    restart: "no"
    ports:
      - "8007:8007"
    depends_on:
      - "kafka"
      - "user-mysql"
    environment:
      - spring.datasource.url=jdbc:mysql://user-mysql:3306/user-db?createDatabaseIfNotExist=True
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.hibernate.ddl-auto=update